version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: msclientes
      POSTGRES_USER: Isaias
      POSTGRES_PASSWORD: 1234
      TZ: America/Guayaquil
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - red-ms
    restart: always

  ms-clientes:
    image: isaiasurb/ms-clientes-nuevo:latest
    container_name: ms-clientes
    ports:
      - "8089:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/msclientes
      SPRING_DATASOURCE_USERNAME: Isaias
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres
    networks:
      - red-ms
    restart: always

volumes:
  db_data:
    name: ms-clientes_db_data

networks:
  red-ms: